### ISSUE TITLE
keine Buchungen möglich ab Dienstag, 30. Juni

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#20]

**Comment by debueb** [comment]
@riggidirob: sorry habe jetzt erst gesehen, dass du schon Tickets aufgemacht hast.

Das ist Absicht. Es ist so eingerichtet, dass man in den nächsten vollen drei Monaten (und dem aktuellen Monat) buchen kann. Also mindestens in den nächsten 90 Tagen. Hintergrund ist, dass für jeden Tag berechnet werden muss, ob ein Platz frei ist. Ist es denn ein Use Case, dass man mehr als 3 Monate im Voraus buchen muss? Wir können die Zeit auch ein bisschen hochsetzen, aber ich denke 3 Monate reichen, oder? Wichtig ist: es ist kein "Hard Limit". Ab April kann man dann bis 31. Juli buchen...

**Comment by riggidirob** [comment]
brauchen wir leider doch.
UNICEF bucht ein Abo für sechs Monate. wir müssten also jeden Monat nachträglich das Abo verlängern. ... wie schwer schlägt es denn ins Gewicht, dass zusätzliche Zeit fürs Rechnen draufgeht? Signifikant? Immerhin wird man während des Rechnens durch einen frechen dicken gelben hüpfenden Ball unterhalten. ;) (Kann man den kleiner machen? die drei punkte von früher fand ich übrigens schicker.)

**Comment by debueb** [comment]
Abos würde man ja über Platz Reservierungen abbilden. Die sind nicht an die 3 Monats Regel gebunden.

Die 3 Monatsregel ist für reguläre Buchungen über /bookings. Für jeden Tag in dem Drop Down Kalender wird berechnet, ob ein Platz frei ist. Man kann das auch ein bisschen erhöhen, aber "unlimited" wie bei Platz Reservierungen geht nicht.
