### ISSUE TITLE
Weiterleitung nach Stornierung

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#22]
wenn ich eine Buchung aus meiner Buchungsbestätigung, die ich per Mail bekommen habe, stornieren möchte, werde ich auf die Seite http://padel.koeln/bookings/booking/1c58931e-7369-490d-9b7a-a03453b810ac/cancel geleitet. Dort muss ich die Stornierung nochmals bestätigen. Nach entsprechendem Klick werde ich aber nirgends weitergeleitet. Ich wusste gar nicht, ob das richtig funktioniert hat und habe einfach nochmal geklickt. ... Besser wäre doch die Weiterleitung auf eine Bestätigungs-Seite („Buchung wurde storniert!“) oder zurück auf die home-Seite.

**Comment by debueb** [comment]
kann ich leider nicht nachvollziehen.

beim ersten mal aufrufen des Storno links und nach Bestätigung kommt:
![img_0888](https://cloud.githubusercontent.com/assets/1895897/6870294/7071171a-d49b-11e4-813f-e7912b23b753.jpg)

beim zweiten mal:
![img_0889](https://cloud.githubusercontent.com/assets/1895897/6870301/75639e14-d49b-11e4-8a38-127e12b007a4.jpg)

Kannst Du das bitte nochmal testen?

**Comment by debueb** [comment]
trifft nur auf Paypal zu

**Comment by debueb** [comment]
paypal sandbox gerade nicht verfügbar :(

**Comment by debueb** [comment]
fixed
