### ISSUE TITLE
[mailto:...] wird in CC verschickt

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#29]
Wenn ich eine Mail an alle Spieler einer Begegnung schicken möchte, werden die Emailadressen im Mailprogramm in CC gepackt. Sollten diese nicht ins "An:"-Feld?

**Comment by debueb** [comment]
ja das ist richtig. aber irgendein smartphone hatte mit mehreren to
empfängern probleme. mit cc läuft es aber

Am Donnerstag, 26. März 2015 schrieb riggidirob :

**Comment by riggidirob** [comment]
ok. dann passt es ja. top!
