### ISSUE TITLE
Fehlermeldung bei manueller Platzreservierung

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#31]
![fehler manuelle platz reservierung](https://cloud.githubusercontent.com/assets/10773902/6868188/b7af5112-d489-11e4-9fd9-3b9c5bb4f70e.png)

Reservierung wurde nicht umgesetzt

**Comment by riggidirob** [comment]
ich glaube, ich hab gerade rausgefunden, dass es mit den Feiertagen zu tun hat. wenn im buchungszeitraum ein Feiertag liegt, werden die Termine nur bis zum ersten Feiertag angenommen.

kann das?

**Comment by dwissk** [comment]
jo das kann gut sein. dann würde die fehlermeldung passen. schaue ich mir an...

**Comment by riggidirob** [comment]
so ist es! habe es nochmal getestet. die sammelt-termin-reservierung funktioniert bis zum ersten Feiertag, der die Buchung unterbricht.

**Comment by debueb** [comment]
feiertage werden nun übersprungen
