### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#33]
In der Navi sollte es einen Reiter mit "Uni-Liga" geben, damit die Spieler zu diesem Thema konkreter geleitet werden.

Mein (erster) Vorschlag für die Sitemap:

- News

1. Uni Liga
  1.1 Tabellen
      1.1.1 Uni-Liga Herren 1. Division 1. Phase
            1.1.1.1 Content: Tabelle
            1.1.1.2 Spiele
                    1.1.1.2.1 Alle Spiele 
                    1.1.1.2.2 Spiele von Padel Fiction
                    1.1.1.2.3 Spiele von ...
            1.1.1.3 Teams
                    1.1.1.3.1 Alle Teams
                    1.1.1.3.2 Padel Fiction
                    1.1.1.3.3 ...
      1.1.2 Uni-Liga Herren 2. Division 1. Phase
            1.1.2.1 Content: Tabelle
            1.1.2.2 Spiele
                    1.1.2.2.1 Alle Spiele 
                    1.1.2.2.2 Spiele von Padel Fiction
                    1.1.2.2.3 Spiele von ...
            1.1.2.3 Teams
                    1.1.2.3.1 Alle Teams
                    1.1.2.3.2 Padel Fiction
                    1.1.2.3.3 ...
      1.1.3 Uni-Liga Herren 3. Division 1. Phase
            1.1.3.1 Content: Tabelle
            1.1.3.2 Spiele
                    1.1.3.2.1 Alle Spiele 
                    1.1.3.2.2 Spiele von Padel Fiction
                    1.1.3.2.3 Spiele von ...
            1.1.3.3 Teams
                    1.1.1.1.1 Alle Teams
                    1.1.1.1.2 Padel Fiction
                    1.1.1.1.3 ...
      1.1.4 Uni-Liga Mixed 1. Division 1. Phase
             1.1.1.1 Content: Tabelle
            1.1.1.2 Spiele
                    1.1.1.1.1 Alle Spiele 
                    1.1.1.1.2 Spiele von Padel Fiction
                    1.1.1.1.3 Spiele von ...
            1.1.1.3 Teams
                    1.1.1.1.1 Alle Teams
                    1.1.1.1.2 Padel Fiction
                    1.1.1.1.3 ...
  1.2 Spieler (--> die Frage ist, ob man diese Liste überhaupt veröffentlichen sollte. 1. Datenschutz und 2. Wahrung von mehr Diskretion. Vielleicht quatschen wir hierüber nochmal genauer.)
      1.2.1 Alle Spieler
      1.2.2 Spieler Uni-Liga Herren 1. Division 1. Phase
      1.2.3 Spieler Uni-Liga Herren 2. Division 1. Phase
      1.2.4 Spieler Uni-Liga Herren 3. Division 1. Phase
      1.2.5 Spieler Uni-Liga Mixed 1. Division 1. Phase
  1.3 Teams
  1.4 Platzbuchung

3. Platzbuchung
  3.1 Uni-Liga
  3.2 Pay & Play

... Alles andere ist gut und könnte aus meiner Sicht so bleiben...

**Comment by debueb** [comment]
Spieler und Teams unter Uni Liga verschieben

Uni Liga
   - Tabellen
   - Spiele
   - Spieler
   - Teams
