### ISSUE TITLE
Uni-Liga Buchung

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#35]
Nach Buchung eines Uni-Liga-Platzes mit Gutschein (in meinem Fall habe ich probeweise Do, 02. April, 19:30 gebucht), ändert sich im Anschluss an der farblichen Anzeige auf der "Platzbuchung"-Seite nichts. Der Uni-Liga-Zeitslot um 19:30 bleibt buchbar.

Wenn ich danach auf diesen Zeitslot klicke (2. April, 19:30 - http://padel.koeln/bookings/2015-04-02/19:30?offer=3), ist als einzige Option "Platz 2 Pay & Play" ausgewählt und per Paypal buchbar. Was schon mal beruhigend ist, weil so Doppelbuchungen ausgeschlossen sind.

**Comment by debueb** [comment]
Ist ein Anzeigefehler. Ich aktualisiere das Portal jetzt, ist in ein paar Min wieder verfügbar.
