### ISSUE TITLE
Gutschein-Option

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#37]
Keine Möglichkeit "Platz 2 Pay & Play" per Gutschein zu buchen.

Kann das??

**Comment by debueb** [comment]
![screen shot 2015-03-30 at 14 26 15](https://cloud.githubusercontent.com/assets/1895897/6896156/a0cf39a6-d6e8-11e4-851c-e0ab1888c1b1.png)

ja, war so konfiguriert. hab's geändert.

**Comment by riggidirob** [comment]
;)
