### ISSUE TITLE
"Leider nix frei" und "nicht verfügbar" zusammenlegen

### ISSUE THREAD

**Issue by debueb** [debueb/padelcampus#38]
Vorschlag: Wir legen die "Leider nix frei" und "nicht verfügbar" Farben zusammen. Es ist zwar für den Admin nett zu wissen, dass hier ein Angebot ausgebucht ist, aber für den Nutzer ist es irrelevant...

Oder?

**Comment by debueb** [comment]
Vorteile:

- weniger bunt
- mehr Platz in der Legende
- schnellere Orientierung für den Nutzer

Nachteile

- etwas weniger Informationen für den Admin

**Comment by riggidirob** [comment]
Robin Breburda hat den "Gefällt mir"-Button gedrückt.
Bitte alle nicht buchbaren Zeiten in grau darstellen.

**Comment by debueb** [comment]
changed
