### ISSUE TITLE
Buchungsabbruch über Paypal

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#41]
Bei Buchungsabbruch wird der Court nicht wieder freigegeben

ich wurde zur Paypal-Login-Seite weitergeleitet habe mich aber noch nicht mal eingelogged und dann die Seite geschlossen. Seit dem ist der Court blockiert.

Habe den Vorgang wiederholt, um sicher zu gehen. = Gleiches Ergebnis. (Do., 02. April)

**Comment by debueb** [comment]
Das ist gewollt. Das muss ich so machen, um Doppelbuchungen zu verhindern. Das gilt nicht nur für PayPal, sondern für alle Buchungsmethoden.

Das Szenario ist folgendes:

User1 wählt Do 02.04 19:00 Uhr aus und zahlt per PayPal. Ich übergebe die Kontrolle an PayPal und warte, bis ich von PayPal die Zahlungsbestätigung habe. User1 hat aber sein Kennwort vergessen, daher dauert der Prozess länger. Sagen wir 15min, um realistisch zu bleiben.

User2 wählt 2min nach User1 das gleiche Datum und die gleiche Zeit aus, zahlt aber per Kreditkarte/Lastschrift/Gutschein/egal. Die Buchung dauert bei ihm nur 2min. 

Wenn ich die Sperre nicht einbauen würde, dann hätten wir eine Doppelbuchung, wenn User1 nach 15min von PayPal zurück kommt.

Das System sollte alle nicht gebuchten Plätze entweder nach Ablauf der User Session oder nach 30 min wieder freigeben.

P.S. Da ich das Problem auch gesehen habe habe ich an den Kalenderkonfigurationen rumgespielt. SR
