### ISSUE TITLE
Problem mit Angebots-Namen (Uni-Liga)

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#42]
![2015-03-30_1817](https://cloud.githubusercontent.com/assets/10773902/6900871/d841e566-d709-11e4-8b36-8eb62093542c.png)

Kann man das dem Kunden nicht im nächsten Schritt separat anzeigen lassen? So wie sich der Preis ja auch ändert je nach dem, welche Spieldauer man im DropDown wählt, könnte sich doch auch eine Zeile mit "Court" oder "Platz" darstellen.

Übrigens: Platz 1 heißt "Barbarossaplatz" und Platz 2 "Brüsseler Platz" ;) Vielleicht kann man das ja noch irgendwo unterbringen.

**Comment by riggidirob** [comment]
Einschub:

So wie sich der Preis ja auch ändert je nach dem, welche Spieldauer man im DropDown wählt, könnte sich doch auch eine Zeile mit "Court" oder "Platz" darstellen, die sich entsprechend der Auswahl des DropDown-Auswahl in der Zeile "Angebot" ändert.

**Comment by debueb** [comment]
das angebot IST der platz. daher macht es keinen sinn ein drop down mit nur 1 option anzubieten. ggf. werde ich ein detail-text-feld zur angebotsdefinition hinzufügen, der nur auf der detailseite dargestellt wird.

**Comment by riggidirob** [comment]
so meinte ich im frontend. und "Court 1 - "Barbarossaplatz" " ändert sich, je nach dem welce option man im drop-down "Angebot" wählt. Damit ist dem Kunden unmissverständlich klar, welchen Court er gebucht hat.

ist das umsetzbar?

![platzbuchung-court](https://cloud.githubusercontent.com/assets/10773902/6919510/edc100b2-d7b7-11e4-85e2-8cae536ecb3d.png)
