### ISSUE TITLE
Robin CMS von padel.koeln erklären

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#45]
Hi Dominik,

damit ich Content-Seiten pflegen kann (z.B. AGBs, Preislisten, ...), wäre es geil, wenn Du mich in das CMS der Seite einweist. Gerade wenn es darum geht kleine inhaltliche Änderungen vorzunehmen (nur auf Textbasis, versteht sich), muss ich spontan darauf zugreifen können, ohne Dir Tasks schreiben zu müssen. Auch wenn ich wüsste, wie ich Links setzen kann (wie diese Navi-Geschichte bei der Uni-Liga), würden wir uns einigen Aufwand sparen können.

Was denkst Du? Wäre das in Ordnung?

**Comment by debueb** [comment]
Ja macht durchaus Sinn, dass Content Pflege nicht zur Entwickler Aufgabe wird. Da habe ich auch keine Lust drauf.

Ich werde vermutlich den Editor aus dem News Bereich für die Footer Links wiederverwenden. Bzgl. Links in der Navigationsbar: die sind momentan nicht vom Admin pflegbar, hier muss ich erst mal schauen, wie flexibel das sein soll usw.

**Comment by debueb** [comment]
Footer Links sind nun unter Admin --> General --> Footer Links administrierbar...
