### ISSUE TITLE
set limits for requests of Spielbörse

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#47]
Es sollte für mich als Spieler der Seilbörse möglich sein, Einladungen, die ich aus der Spielbörse bekomme, nach Leveln zu filtern.

Beispiel:
Ich bin Level 3,5 und möchte ausschließlich Einladungen von Spielern erhalten die Level selbst mindestens 3,5 sind. Somit würde eine Einladung eines 2,0-Spielers, der - aus welchen Gründen auch immer - ein Gesuch für Level 2,0 bis 5,0 aufgegeben hat, nicht zu mir weitergeleitet werden.

So kann man zumindest auch einmischen selbst bestimmen, welche Einladungen man bekommt.

Umsetzbar?

**Comment by debueb** [comment]
1. es gibt keine halben level
2. spieler müssen nicht zwingend ihr spielniveau angeben, d.h. eine Filterung nach Spielerniveau ist aus diesem Aspekt momentan problematisch

Das Feature können wir auch nachträglich einbauen. Ich bin mir nicht sicher, wie stark die Spielbörse genutzt werden wird. Falls es sich als nervig herausstellen sollte zu viele Spielangebote zu erhalten bauen wir eine solche Filterung ein.
