### ISSUE TITLE
Navi

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#49]
Bitte Navi-Menü ändern:

- Pay&Play (neu oben in die Navi-Leiste einfügen)
- - Platzbuchung
- - Kurse & Training (kommt noch)
- - Preisliste (Content habe ich im "Footer-Link" eingefügt)

...so haben wir im Footer später AGBs, Impressum und Datenschutz.

**Comment by debueb** [comment]
Unter Administration --> Allgemein --> Module können nun beliebige statische Seiten hinzugefügt und Menü Einträge verschoben werden. Hier finden sich nun auch die Footer und Blog Einträge wieder.

**Comment by riggidirob** [comment]
wie verschiebe ich den Menüpunkt "Platzbuchung" als Unterpunkt in den Münupunkt "Pay&Play"?

im issue oben wollte ich darstellen, dass "Pay&Play" der übergeordnete menüpunkt sein soll (wie z.B. bei "Uni-Liga") und die folgenden Seiten ("Platzbuchung", "Kurse", "Preisliste") als unterpunkte eingefügt werden (wie "Tabellen", "Spieler", "Spiele", "Teams").

**Comment by dwissk** [comment]
So flexibel ist das leider nicht. Man kann nur einzelne Menüpunkte hinzufügen und verschieben, nicht verschachteln.
