### ISSUE TITLE
Farbschema

### ISSUE THREAD

**Issue by riggidirob** [debueb/padelcampus#50]
Braun ersetzen durch einen Orange-Ton.
Zwei zur Auswahl: #f5a81c (255, 160, 16) oder #ec6410 (255, 100, 16)

**Comment by debueb** [comment]
hab ich geändert... aber wirklich fan bin ich davon nicht... bisschen zu aggressiv der farbton oder?

**Comment by riggidirob** [comment]
find ich auf jeden fall besser, als das braun.

hast du denn #f5a81c genommen?
wenn ja, nimm doch mal den #ec6410. mal schauen, wie das wirkt.

- die Überschrift ("Links") ist etwas grau eingefärbt. kann das? es wirkt auf jeden fall dunkler, als die übrige orangene Schrift.
- genauso die Unterüberschrift ("nützliche Links"). das ist kein helles weiß, so wie im Menü oder im Footer
- und den "hover" auch noch von braun in die entsprechende Farbe ändern

![farbschema](https://cloud.githubusercontent.com/assets/10773902/7420710/0497d7fa-ef7f-11e4-9c23-90c730ce4017.jpg)

**Comment by riggidirob** [comment]
ok. die Überschrift ist die selbe Farbe (sagt Photoshop). dann wirkt das so, wegen des weißen Hintergrunds.

![farbschema2](https://cloud.githubusercontent.com/assets/10773902/7420800/cd43ea2c-ef7f-11e4-92fb-c5bd8a823e94.jpg)
